version: '3.8'

services:
  db:
    image: postgres:13
    container_name: booking_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookings
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: booking_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/bookings
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"

volumes:
  postgres_data:
